# /// script
# requires-python = ">=3.11"
# dependencies = ["PyYAML==6.0.3", "markdown-it-py==4.0.0"]
# ///
"""Print the sorted byte-hash manifest without writing any documents."""
from __future__ import annotations

import argparse
import json
import sys

# Installed skill packages stay free of generated bytecode.
sys.dont_write_bytecode = True
from pathlib import Path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--project-root', required=True, type=Path)
    parser.add_argument('--change', required=True)
    parser.add_argument('--stage', required=True, choices=('documents', 'plan'))
    args = parser.parse_args(argv)
    try:
        from lib.documents import InputError, ValidationError
        from lib.snapshots import snapshot
    except ImportError as exc:
        print(json.dumps({'code': 'environment', 'message': str(exc)}), file=sys.stderr)
        return 2
    try:
        result = snapshot(args.project_root.resolve(strict=True), args.change, args.stage)
    except (InputError, ValidationError, OSError, UnicodeError) as exc:
        print(json.dumps({'code': getattr(exc, 'code', 'input_unreadable'),
                          'path': str(getattr(exc, 'path', args.project_root)),
                          'message': getattr(exc, 'message', str(exc))}, ensure_ascii=False),
              file=sys.stderr)
        return 2 if isinstance(exc, (InputError, OSError, UnicodeError)) else 1
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == '__main__':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')
    raise SystemExit(main())
